### PR TITLE
Update generic-sensors-adapter.

### PR DESCRIPTION
**Pull request by mrstegeman**

### CODE REVIEW

**Comment by mrstegeman** [comment]
@rzr looks like we're getting some checksum failures.

**Comment by mrstegeman** [comment]
Ah, it looks like there were actually some issues building the dependencies on Node 14, e.g. the `linux-arm, node:14` build here: https://github.com/rzr/generic-sensors-webthings/runs/1266889924?check_suite_focus=true

**Comment by rzr** [comment]
Packages are released though:

https://github.com/rzr/generic-sensors-webthings/releases/tag/v0.0.15

**Comment by mrstegeman** [comment]
I know, but the dependencies are failing to build on Node 14.

**Pull request merged**
