### PR TITLE
Update voco.

### PR DESCRIPTION
**Pull request by mrstegeman**

### CODE REVIEW

**Comment by mrstegeman** [comment]
@createcandle 👍🏻

**Comment by createcandle** [comment]
I noticed an error locally, which I believe I've also seen on a github log.

```
Installing collected packages: rapidfuzz, pyalsaaudio, six, python-dateutil, pytz, paho-mqtt, certifi, chardet, idna, urllib3, requests
  Running setup.py install for rapidfuzz ... done
  Running setup.py install for pyalsaaudio ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-w8z8qb1b/pyalsaaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-2sx2c8v4/install-record.txt --single-version-externally-managed --prefix  --compile --home=/tmp/pip-target-mrv8e50z:
    running install
    running build
    running build_ext
    building 'alsaaudio' extension
    creating build
    creating build/temp.linux-armv7l-3.7
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -c alsaaudio.c -o build/temp.linux-armv7l-3.7/alsaaudio.o
    alsaaudio.c:28:10: fatal error: alsa/asoundlib.h: No such file or directory
     #include <alsa/asoundlib.h>
              ^~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-w8z8qb1b/pyalsaaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-2sx2c8v4/install-record.txt --single-version-externally-managed --prefix  --compile --home=/tmp/pip-target-mrv8e50z" failed with error code 1 in /tmp/pip-install-w8z8qb1b/pyalsaaudio/
```


It would theoretically be fixed by running:
```
sudo apt-get install libasound2-dev
```

Should I perhaps add that to the `package.sh` script?

**Comment by mrstegeman** [comment]
I already did that for you the other day: https://github.com/createcandle/voco/blob/master/package.sh#L10

**Comment by createcandle** [comment]
Brilliant, thanks!

**Pull request merged**
