### PR TITLE
Update macrozilla.json

### PR DESCRIPTION
**Pull request by bewee**

### CODE REVIEW

**Review by mrstegeman — APPROVED** [review]

**Comment by bewee** [comment]
Hm, these changes seem not to be reflected on the add-on list yet. Is this normal? (Just asking because I seem to remember that last time this took only a few minutes after merge was complete)

**Comment by mrstegeman** [comment]
Looks up-to-date to me: https://api.webthings.io:8443/addons?version=1.0.0&node=64&query=macro

**Comment by bewee** [comment]
For me, this link shows v0.1.9, the old version🤔

**Comment by mrstegeman** [comment]
Try again please.

**Comment by bewee** [comment]
That did it! Thank you very much😅

**Pull request merged**
