### PR TITLE
Create macrozilla.json

### PR DESCRIPTION
**Pull request by Galveston01**

### CODE REVIEW

**Comment by Galveston01** [comment]
Honestly I don't know what's the problem here :/

**Comment by mrstegeman** [comment]
The files inside `lib/` are not being checksummed.

**Comment by Galveston01** [comment]
Guess that finally worked out

**Comment by mrstegeman** [comment]
This is phenomenal!!

A few quick thoughts here.
1. This will need to be cross-compiled, as there are native node libraries. @tim-hellhake has figured out how to do this without having to add your repo to the addon-builder, but it instead directly uses the builder's toolchains. See [here](https://github.com/tim-hellhake/influxdb-bridge/commit/4ad0c70df297f4c49c4192975c46d94e03fcfd71).
2. I would prefer that you didn't insert random things into the gateway's database. Instead, you should create your own database inside the data directory, e.g. `~/.mozilla-iot/data/macrozilla`. You can access that directory from your APIHandler via `this.userProfile.dataDir`.
3. You might want to consider renaming the add-on. When I first saw the name, I thought it was for [this](https://www.macrozilla.info/) and was really confused.

**Comment by Galveston01** [comment]
1. As far as I can see I have copied everything to my workflow. But unfortunately the action fails with the following error:
```
> bufferutil@4.0.1 install /home/runner/work/macrozilla/macrozilla/node_modules/bufferutil
> node-gyp-build


> utf-8-validate@5.0.2 install /home/runner/work/macrozilla/macrozilla/node_modules/utf-8-validate
> node-gyp-build


> websocket@1.0.31 install /home/runner/work/macrozilla/macrozilla/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/home/runner/work/macrozilla/macrozilla/node_modules/websocket/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
npm ERR! missing script: build
make: Leaving directory '/home/runner/work/macrozilla/macrozilla/node_modules/websocket/build'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-09-29T18_42_15_636Z-debug.log

> node-cron@2.0.3 postinstall /home/runner/work/macrozilla/macrozilla/node_modules/node-cron
> opencollective-postinstall

added 249 packages in 6.955s
Error: Process completed with exit code 1.
```
Since I have quite no experience with github actions, could you probably have a look at it ([here](https://github.com/Galveston01/macrozilla/tree/crosscompile))?

2. That sounds reasonable, gonna do that.

3. Changed display name to only "Macros" and will create new PR here as soon as 1. and 2. are ready

**Comment by mrstegeman** [comment]
https://github.com/Galveston01/macrozilla/pull/3

**Comment by Galveston01** [comment]
This worked for the build actions as well as `create-release`, but `build (linux-x64, node:10)` and `build (linux-x64, node:12)` still fail:
```
Run actions/upload-release-asset@v1.0.1
Error: ENOENT: no such file or directory, stat 'macrozilla-v0.1.4-linux-x64-v10.tgz'
```
The other release actions are all canceled.

**Comment by mrstegeman** [comment]
https://github.com/Galveston01/macrozilla/pull/5

**Pull request merged**
