### PR TITLE
Webtio hydroqc addon v0.2 beta

### PR DESCRIPTION
**Pull request by arist0v**
Upgrade library
minor bug fix

### CODE REVIEW

**Comment by tim-hellhake** [comment]
Addon are expected to use [semantic versioning](https://semver.org/).
You have to use `0.2.0`.

**Comment by tim-hellhake** [comment]
Addons are expected to use [semantic versioning](https://semver.org/).
You have to use `0.2.0`.

**Comment by arist0v** [comment]
version updated to semantic standard

**Comment by tim-hellhake** [comment]
The `short_name` is too long (max 12 chars).
You can use `Hydro Quebec`.

**Review by tim-hellhake — CHANGES_REQUESTED** [review]
The `short_name` is too long (max 12 chars).
You can use `Hydro Quebec`.

**Comment by arist0v** [comment]
shortname fixed

**Review by tim-hellhake — CHANGES_REQUESTED** [review]
Please update the checksum :smile:
Sorry, it's a bit tedious.
On your next PR, the workflow should run automatically.

**Comment by arist0v** [comment]
checksum fixed, workflow still waiting approval

**Review by tim-hellhake — CHANGES_REQUESTED** [review]
Ok, now it's the `author`.
It must match the manifest of your addon.

**Comment by tim-hellhake** [comment]
It shouldn't be `WebThingsIO` anyway :smile:

**Comment by arist0v** [comment]
done, i must have been drunk or something when i have done this :P or i have copied the .json from another project and maybe didn'T look at the object name and just changed some part lol sorry

**Review by tim-hellhake — CHANGES_REQUESTED** [review]
`Name mismatch for package "webtio-hydroqc-addon": name from manifest.json "Hydro Quebec Winter Credit program" doesn't match name from webtio-hydroqc-addon.json "Hydro-Quebec Winter Credit Adddon"`

**Comment by arist0v** [comment]
fixed!

**Comment by arist0v** [comment]
sorry, look like github haven'T updated, now it should be OK

**Comment by tim-hellhake** [comment]
🎉

**Comment by arist0v** [comment]
Thank you i'm really glad this is my first ever real project!!!!

**Pull request merged**
